hl.gesture({ fingers = 4, direction = "horizontal", action = "workspace" })

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "-1" }))
hl.bind("CONTROL + L", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("CONTROL + H", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + Right", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + Left", hl.dsp.focus({ workspace = "-1" }))
hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }))
-- hl.bind("SUPER + N", hl.dsp.window.cyclenext())
hl.bind("SUPER+CONTROL + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER+CONTROL + L", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER+CONTROL + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER+CONTROL + J", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER+ALT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind("SUPER+ALT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind("SUPER+ALT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind("SUPER+ALT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind("SUPER+ALT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind("SUPER+ALT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind("SUPER+ALT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind("SUPER+ALT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind("SUPER+ALT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind("SUPER+ALT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))
hl.bind("SUPER+CONTROL + S", hl.dsp.window.move({ workspace = "special" }))
-- hl.bind("SUPER + Semicolon", hl.dsp.splitratio({ -0.1 }))
-- hl.bind("SUPER + Apostrophe", hl.dsp.splitratio({ "+0.1" }))
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ 0 }))
-- PATTERN: 10 sequential binds collapsed to loop
for i = 1, 10 do
    hl.bind("SUPER + " .. (i % 10), hl.dsp.focus({ workspace = tostring(i % 10) }))
end

hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("special"))
hl.bind("CONTROL + SPACE", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + R", function()
    hl.exec_cmd("killall waybar; waybar")
end)
hl.bind("SUPER+SHIFT + R", function()
    hl.exec_cmd("killall swww-daemon; swww-daemon --format xrgb &")
end)
hl.bind("SUPER+SHIFT + H", function()
    hl.exec_cmd("pkill fuzzel || cliphist list | fuzzel  --match-mode fzf --dmenu | cliphist decode | wl-copy")
end)
hl.bind("SUPER+CONTROL+ALT + T", function()
    hl.exec_cmd("grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l eng \"tmp.png\" - | wl-copy && rm \"tmp.png\"")
end)
hl.bind("SUPER+CONTROL+ALT + E", function()
    hl.exec_cmd("grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l eng \"tmp.png\" - | wl-copy && rm \"tmp.png\"")
end)
hl.bind("SUPER+CONTROL+ALT + C", function()
    hl.exec_cmd("grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l chi_sim \"tmp.png\" - | wl-copy && rm \"tmp.png\"")
end)
hl.bind("SUPER+CONTROL+ALT + F", function()
    hl.exec_cmd("grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l fra \"tmp.png\" - | wl-copy && rm \"tmp.png\"")
end)
hl.bind("SUPER+CONTROL + T", function()
    hl.exec_cmd("~/.config/hypr/external/ags/scripts/color_generation/switchwall.sh")
end)
hl.bind("SUPER+SHIFT + S", function()
    hl.exec_cmd("~/.config/hypr/scripts/grimblast.sh --freeze copy area")
end)
hl.bind("SUPER+SHIFT+CONTROL + S", function()
    hl.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -")
end)
hl.bind(" + XF86AudioMute", function()
    hl.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%")
end, { locked = true })
hl.bind(" + XF86AudioRaiseVolume", function()
    hl.exec_cmd("wpctl set-volume -l 1.1 @DEFAULT_AUDIO_SINK@ 5%+")
end, { locked = true, longpress = true })
hl.bind(" + XF86AudioLowerVolume", function()
    hl.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-")
end, { locked = true, longpress = true })
hl.bind("SUPER+SHIFT + T", function()
    hl.exec_cmd("grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l eng \"tmp.png\" - | wl-copy && rm \"tmp.png\"")
end)
hl.bind("SUPER+SHIFT + F", function()
    hl.exec_cmd("grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l fra \"tmp.png\" - | wl-copy && rm \"tmp.png\"")
end)
hl.bind("SUPER + T", function()
    hl.exec_cmd("kitty")
end)
hl.bind("SUPER + E", function()
    hl.exec_cmd("dolphin")
end)
hl.bind("SUPER+CONTROL + Space", function()
    hl.exec_cmd("pkill ~/.config/rofi/launchers/type-1/launcher.sh || ~/.config/rofi/launchers/type-1/launcher.sh")
end)
hl.bind("SUPER + W", hl.dsp.window.close("activewindow"))
hl.bind("SUPER + Q", hl.dsp.window.close("activewindow"))
hl.bind(" + XF86AudioPlay", function()
    hl.exec_cmd("playerctl play-pause")
end, { locked = true })
hl.bind(" + XF86AudioNext", function()
    hl.exec_cmd("playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`")
end, { locked = true })
hl.bind(" + XF86AudioPrev", function()
    hl.exec_cmd("playerctl previous")
end, { locked = true })
hl.bind("SUPER+SHIFT + 4", function()
    hl.exec_cmd("playerctl previous")
end, { locked = true })
hl.bind(" + XF86MonBrightnessUp", function()
    hl.exec_cmd("brightnessctl set '5000+'; ddcutil setvcp 10 + 10")
end, { locked = true, longpress = true })
hl.bind(" + XF86MonBrightnessDown", function()
    hl.exec_cmd("brightnessctl set '5000-'; ddcutil setvcp 10 - 10")
end, { locked = true, longpress = true })
-- hl.bind("CONTROL + K", hl.dsp.movecurrentworkspacetomonitor({ "DP-3" }))
-- hl.bind("CONTROL + J", hl.dsp.movecurrentworkspacetomonitor({ "eDP-1" }))
