# ######## Window rules ########
windowrule = match:title .* noblur
windowrule = match:title ^(blueberry.py)$, float on
windowrule = match:title ^(steam)$, float on
windowrule = match:title ^(Waydroid)$, float on
windowrule = match:title ^(Android Emulator)(.*)$, float on
windowrule = match:title ^(guifetch)$, float on # FlafyDev/guifetch
windowrule = match:class (dev.warp.Warp), tile on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^(Open File)(.*)$, center on
windowrule = match:title ^(Select a File)(.*)$, center on
windowrule = match:title ^(Choose wallpaper)(.*)$, center on
windowrule = match:title ^(Open Folder)(.*)$, center on
windowrule = match:title ^(Save As)(.*)$, center on
windowrule = match:title ^(Library)(.*)$, center on
windowrule = match:title ^(File Upload)(.*)$, center on
windowrule = match:title ^(Screenkey)(.*)$, center on

# Picture-in-Picture
windowrulev2 = keepaspectratio, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = move 73% 72%,title:^(Picture(-| )in(-| )[Pp]icture)$ 
windowrulev2 = size 25%, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = float, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = pin, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = opacity 0.9 0.9,class:^(kitty)$
windowrulev2 = opacity 0.8 0.8,class:^((t|T)hunar)$

# Dialogs
windowrule=match:title ^(Open File)(.*)$, float on
windowrule=match:title ^(Select a File)(.*)$, float on
windowrule=match:title ^(Choose wallpaper)(.*)$, float on
windowrule=match:title ^(Open Folder)(.*)$, float on
windowrule=match:title ^(Save As)(.*)$, float on
windowrule=match:title ^(Library)(.*)$, float on
windowrule=match:title ^(File Upload)(.*)$, float on

# Tearing
windowrule=match:title .*\.exe, float on
windowrule=match:title .*\.exe, immediate on
windowrule=match:class (steam_app), immediate on

# No shadow for tiled windows
windowrulev2 = noshadow,floating:0

# ######## Layer rules ########
layerrule = match:namespace .*, xray on
layerrule = match:namespace walker, no_anim on
layerrule = match:namespace selection, no_anim on
layerrule = match:namespace overview, no_anim on
layerrule = match:namespace anyrun, no_anim on
layerrule = match:namespace indicator.*, no_anim on
layerrule = match:namespace osk, no_anim on
layerrule = match:namespace hyprpicker, no_anim on
layerrule = match:namespace shell:*, blur on
layerrule = match:namespace shell:*, ignore_alpha 0.6

layerrule = match:namespace noanim, no_anim on
layerrule = match:namespace gtk-layer-shell, blur on
# layerrule = ignorezero, gtk-layer-shell
layerrule = match:namespace launcher, blur on
layerrule = match:namespace launcher, ignore_alpha 0.5
layerrule = match:namespace notifications, blur on
layerrule = match:namespace notifications, ignore_alpha 0.69

# ags
layerrule = match:namespace sideleft.*, animation slide top
layerrule = match:namespace sideright.*, animation slide top
layerrule = match:namespace session, blur on

layerrule = match:namespace bar, blur on
layerrule = match:namespace bar, ignore_alpha 0.6
layerrule = match:namespace corner.*, blur on
layerrule = match:namespace corner.*, ignore_alpha 0.6
layerrule = match:namespace dock, blur on
layerrule = match:namespace dock, ignore_alpha 0.6
layerrule = match:namespace indicator.*, blur on
layerrule = match:namespace indicator.*, ignore_alpha 0.6
layerrule = match:namespace overview, blur on
layerrule = match:namespace overview, ignore_alpha 0.6
layerrule = match:namespace cheatsheet, blur on
layerrule = match:namespace cheatsheet, ignore_alpha 0.6
layerrule = match:namespace sideright, blur on
layerrule = match:namespace sideright, ignore_alpha 0.6
layerrule = match:namespace sideleft, blur on
layerrule = match:namespace sideleft, ignore_alpha 0.6
layerrule = match:namespace indicator*, blur on
layerrule = match:namespace indicator*, ignore_alpha 0.6
layerrule = match:namespace osk, blur on
layerrule = match:namespace osk, ignore_alpha 0.6

